cy46_wfp_ref: 

  file_templates : ['fc2022071112+%Hgrib2_fp','fc2022071112+%Hgrib_sfxs']

  atos:
     path_template : 'ec:/nkac/harmonie/NL25_Eunice_n0/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/NL13_Eunice_n1/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/NL750_Eunice_n2/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/NL25_Eunice_n0_NOWFP/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/NL13_Eunice_n1_NOWFP/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/NL750_Eunice_n2_NOWFP/%Y%m%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 2500,1300,750
     levels : 90

