AIB_43h221_de:

  file_templates : ['fc%Y%m%d%H+%LLLgrib2_fp','ICMSHHARM+0%LLL']

  atos:
     path_template : 'ec:/mdk/harmonie/AIB_43h221_de/%Y/%m/%d/%H/'

  domain : 
     name : 'IBERIAxl_2.5'
     resolution : 2500
     levels : 65

AIB_DEODE_Beta:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp','ICMSHHARM+0%LLL']

  atos:
     path_template : 'ectmp:/sp0c/harmonie/AIB_DEODE_Beta/%Y/%m/%d/%H/'

  domain : 
     name : 'IBERIAxl_2.5'
     resolution : 2500
     levels : 65


VAL500m_de:
  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp','ICMSHHARM+0%LLL','ICMSHHARM+0%LLL.sfx']

  atos:
     path_template : 'ec:/mdk/harmonie/VAL500m_de/%Y/%m/%d/%H/'

  domain :
     name : 'MEDv_0.5'
     resolution : 500
     levels : 65





