cy46_aq_ref: 

  file_templates : ['fc2022071112+%Hgrib2_fp','fc2022071112+%Hgrib_sfxs']

  atos:
     path_template : 'ec:/nkac/harmonie/BL2_n0_2500m/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/BL2_n1_1300m/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/BL2_n2_750m/%Y%m%d/%H/' 
     path_template : 'ec:/nkac/harmonie/BL19_n0_2500m/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/BL19_n1_1300m/%Y%m%d/%H/'
     path_template : 'ec:/nkac/harmonie/BL19_n2_750m/%Y%m%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 2500,1300,750
     levels : 90
